pason_webchat_homepage:
    pattern:  /
    defaults: { _controller: PasonWebchatBundle:Default:index }

pason_webchat_chat:
    pattern:  /chat
    defaults: { _controller: PasonWebchatBundle:Default:chat }

pason_webchat_user:
    pattern:  /getuser
    defaults: { _controller: PasonWebchatBundle:Default:getuser }
    
    